spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root

  mvc.view:
    prefix: /WEB-INF/
<<<<<<< HEAD
    suffix: .jsp
=======
    suffix: .jsp
>>>>>>> ef4d6190760680ba2f510be91b72153dc32ba33b
